function varOut = GaussSeidelSolve(varIn,coeffs,source,softening)
%Solves a linear 2D-system by means of under-relaxed gauss-seidel.
%varIn: The variable being solved (MxN matrix)
%coeffs: The linear coefficients for the neighbouring nodes (MxNx5 matrix)
%source: Source-term vector (MxN matrix)
%softening: The under relaxation factor (float greater than 0 and smaller
%or equal to 1, where 1 is no underrelaxation
varOut = varIn;
for i=2:size(varOut,1)-1
    for j = 2:size(varOut,2)-1
        varOut(i,j) = softening*(...
                                    coeffs(i,j,1) * varOut(i+1,j) +...
                                    coeffs(i,j,2) * varOut(i-1,j) +...
                                    coeffs(i,j,3) * varOut(i,j+1) +...
                                    coeffs(i,j,4) * varOut(i,j-1) +...
                                    source(i,j)...
                                )/coeffs(i,j,5)+...
                     (1-softening)*varOut(i,j);
    end
end
end