% Rhie-Chow
for i = 2:cI-2
    for j = 2:cJ-1
        for k = 2:cK-1
        Ue(i,j,k) = (U(i,j,k,timestep)+U(i+1,j,k,timestep))./2+...
                    alphaUV.*dz_C(i,j,k).*dy_C(i,j,k)./((coeffsUV(i,j,k,8))*4).*...
                    (...
                    P(i+2,j,k,timestep)-...
                  3*P(i+1,j,k,timestep)+...
                  3*P(i+0,j,k,timestep)-...
                    P(i-1,j,k,timestep)...
                    );
        end
    end
end
for i = 2:cI-1
    for j = 2:cJ-2
        for k = 2:cK-1
            Vn(i,j,k) = (V(i,j,k,timestep)+V(i,j+1,k,timestep))./2+...
                        alphaUV.*dz_C(i,j,k).*dx_C(i,j,k)./((coeffsUV(i,j,k,8))*4).*...
                        (...
                        P(i,j+2,k,timestep)-...
                      3*P(i,j+1,k,timestep)+...
                      3*P(i,j+0,k,timestep)-...
                        P(i,j-1,k,timestep)...
                        );
        end
    end
end
for i = 2:cI-1
    for j = 2:cJ-1
        for k = 2:cK-2
            Wu(i,j,k) = (W(i,j,k,timestep)+W(i,j,k+1,timestep))./2+...
                        alphaUV.*dx_C(i,j,k).*dy_C(i,j,k)./((coeffsUV(i,j,k,8))*4).*...
                        (...
                        P(i,j,k+2,timestep)-...
                      3*P(i,j,k+1,timestep)+...
                      3*P(i,j,k+0,timestep)-...
                        P(i,j,k-1,timestep)...
                        );
        end
    end
end