function varOut = TimeGaussSeidel(varIn,varOld,coeffs,source)
%varIn: The variable being solved (MxN matrix)
%varOld: Variable values at prior timestep
%coeffs: The linear coefficients for the neighbouring nodes in space and time
%(MxNx6 matrix)
%source: Source-term vector (MxN matrix)
%softening: The under relaxation factor (float greater than 0 and smaller
%or equal to 1, where 1 is no underrelaxation
varOut = varIn;
for i=2:size(varOut,1)-1
    for j = 2:size(varOut,2)-1
        for k = 2:size(varOut,3)-1
        varOut(i,j,k) = (...
                        coeffs(i,j,k,1) * varOut(i+1,j,k) +...
                        coeffs(i,j,k,2) * varOut(i-1,j,k) +...
                        coeffs(i,j,k,3) * varOut(i,j+1,k) +...
                        coeffs(i,j,k,4) * varOut(i,j-1,k) +...
                        coeffs(i,j,k,5) * varOut(i,j,k+1) +...
                        coeffs(i,j,k,6) * varOut(i,j,k-1) +...
                        coeffs(i,j,k,7) * varOld(i,j,k) + ...
                        source(i,j,k)...
                      )/coeffs(i,j,k,8);
        end
    end
end
end